# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='gram/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(upload_to='gramys/'),
        ),
    ]
